"""adding name_firs and name_second

Revision ID: 2516f40ba48b
Revises: 
Create Date: 2024-01-16 18:44:27.569698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2516f40ba48b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_first', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('name_last', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_users_username_email', ['username', 'email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_username_email', type_='unique')
        batch_op.drop_column('name_last')
        batch_op.drop_column('name_first')

    # ### end Alembic commands ###
