"""adding STCG, LTCG, STCG_tax, LTCG_tax

Revision ID: 2e379e41bb75
Revises: dd7cf5c1ac25
Create Date: 2024-01-30 16:16:14.182079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e379e41bb75'
down_revision = 'dd7cf5c1ac25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('STCG', sa.Float(precision=2), nullable=True))
        batch_op.add_column(sa.Column('LTCG', sa.Float(precision=2), nullable=True))
        batch_op.add_column(sa.Column('STCG_tax', sa.Float(precision=2), nullable=True))
        batch_op.add_column(sa.Column('LTCG_tax', sa.Float(precision=2), nullable=True))
        batch_op.drop_column('capital_gains')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capital_gains', sa.FLOAT(), nullable=True))
        batch_op.drop_column('LTCG_tax')
        batch_op.drop_column('STCG_tax')
        batch_op.drop_column('LTCG')
        batch_op.drop_column('STCG')

    # ### end Alembic commands ###
