"""Adding shares_outstanding to Transaction

Revision ID: 318ebf8a7027
Revises: 
Create Date: 2024-01-30 10:23:30.550754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '318ebf8a7027'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shares_outstanding', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('shares_outstanding')

    # ### end Alembic commands ###
