"""removing currency from Listing

Revision ID: 934780e8fc4f
Revises: 
Create Date: 2024-01-27 14:39:11.885580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934780e8fc4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_column('currency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('currency', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
