"""adding capital_gains

Revision ID: 95dbfe24ade5
Revises: 318ebf8a7027
Create Date: 2024-01-30 15:38:38.327172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95dbfe24ade5'
down_revision = '318ebf8a7027'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capital_gains', sa.Float(precision=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_column('capital_gains')

    # ### end Alembic commands ###
