"""Making cash_initial nullable=False

Revision ID: 9a382f446520
Revises: ed5c83a9a1ca
Create Date: 2024-02-02 19:53:24.777437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a382f446520'
down_revision = 'ed5c83a9a1ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('cash_initial',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('cash_initial',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
