"""adding capital_gains and renaming shares -> transaction_shares

Revision ID: dd7cf5c1ac25
Revises: 95dbfe24ade5
Create Date: 2024-01-30 15:40:34.848552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd7cf5c1ac25'
down_revision = '95dbfe24ade5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_shares', sa.Integer(), nullable=False))
        batch_op.drop_column('shares')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shares', sa.INTEGER(), nullable=False))
        batch_op.drop_column('transaction_shares')

    # ### end Alembic commands ###
